version: "3.8"

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: "sponsorcord"
      MYSQL_USER: "sponsorcord"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
    ports:
      - 3306:3306
    expose:
      - 3306
